const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String HomeViewRoute = "HomeView";
const String BrowseViewRoute = "BrowseView";
const String CanteenViewRoute = "CanteenView";
const String ProfileViewRoute = "ProfileView";
const String StartUpViewRoute = "StartUpView";
const String PendingViewRoute = "PendingView";
const String SearchViewRoute = "SearchView";
const String CartViewRoute = "CartView";
const String ModifyViewRoute = "ModifyView";
// Generate the views here